repo has been updated with latest go-runner repo and updating CR
Signed-off-by: Oum Kale <oumkale@chaosnative.com>

diff --git a/build/push b/build/push
--- a/build/push
+++ b/build/push
@@ -1,14 +1,35 @@
 #!/bin/bash
 set -e
 
-IMAGEID=$( docker images -q litmuschaos/litmus-python)
+if [ -z "${REPONAME}" ]
+then 
+  REPONAME="litmuschaos"
+fi
 
-if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
+if [ -z "${IMGNAME}" ] || [ -z "${IMGTAG}" ]; 
 then
+  echo "Image details are missing. Nothing to push."; 
+  exit 1
+fi
+
+IMAGEID=$( docker images -q ${REPONAME}/${IMGNAME}:${IMGTAG} )
+
+if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
+then 
   docker login -u "${DNAME}" -p "${DPASS}";
-  #Push to docker hub repository with latest tag
-  docker tag ${IMAGEID} litmuschaos/litmus-python:ci
-  docker push litmuschaos/litmus-python:ci;
+  # Push image to docker hub
+  echo "Pushing ${REPONAME}/${IMGNAME}:${IMGTAG} ..."; 
+  docker buildx build --file build/Dockerfile --push --progress plane --platform linux/arm64,linux/amd64 --no-cache --tag ${REPONAME}/${IMGNAME}:${IMGTAG} .
+  if [ ! -z "${RELEASE_TAG}" ] ; 
+  then
+    # Push with different tags if tagged as a release
+    # When github is tagged with a release, then Travis will 
+    # set the release tag in env RELEASE_TAG
+    echo "Pushing ${REPONAME}/${IMGNAME}:${RELEASE_TAG} ..."; 
+    docker buildx build --file build/Dockerfile --push --progress plane --platform linux/arm64,linux/amd64 --no-cache --tag ${REPONAME}/${IMGNAME}:${RELEASE_TAG} .
+    echo "Pushing ${REPONAME}/${IMGNAME}:latest ..."; 
+    docker buildx build --file build/Dockerfile --push --progress plane --platform linux/arm64,linux/amd64 --no-cache --tag ${REPONAME}/${IMGNAME}:latest .
+  fi;
 else
-  echo "No docker credentials provided. Skip uploading litmuschaos/litmus-python:ci to docker hub";
+  echo "No docker credentials provided. Skip uploading ${REPONAME}/${IMGNAME}:${IMGTAG} to docker hub"; 
 fi;
